use_frameworks!

target 'UILayoutSpec_Example' do
  pod 'UILayoutSpec', :path => '../'

  target 'UILayoutSpec_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
